[package]
name = "wasm_host"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmtime = { version = "33.0.0", features = ["runtime"]}
wasmtime-wasi = "33.0.0"
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }